# Woodpecker CI Konfiguration als Alternative zu Forgejo Actions
# Um Woodpecker CI zu nutzen:
# 1. Antrag stellen: https://codeberg.org/Codeberg/Community/issues
# 2. Repository auf https://ci.codeberg.org aktivieren

when:
  branch: [master, main]
  event: [push, pull_request]

matrix:
  PYTHON_VERSION:
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"

steps:
  test:
    image: python:${PYTHON_VERSION}-slim
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install flake8
      - echo "Linting mit flake8..."
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - echo "Python Syntax prüfen..."
      - python -m py_compile perlentaucher.py
      - echo "Test: --help Option..."
      - python perlentaucher.py --help
      - echo "Test: Dry-run..."
      - python perlentaucher.py --limit 1 --loglevel DEBUG --download-dir /tmp/test_downloads || true

